import { defineStore } from 'pinia';
import type { Quiz } from 'src/types/Quiz';
import { ref } from 'vue';

export const useQuizStore = defineStore('quizStore', () => {
  const quizList = ref<Quiz[]>(TS_QUIZ_LIST);

  const reset = (): void => {
    //debugger

    quizList.value.forEach((quiz) => {
      quiz.isShowed = false;
    });

    //debugger

    // Vue に変更を検知させるため、新しい配列として代入
    quizList.value = [...quizList.value];
  };

  return { quizList, reset };
});

const TS_QUIZ_LIST: Quiz[] = [
  {
    questionCode: null,
    questionText: 'TSで、プリミティブ型は以下のうちどれか',
    options: { a: 'Object', b: '{}', c: 'Array', d: 'undefined' },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/values-types-variables/primitive-types',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '変数宣言において、letとconstはそれぞれ再代入できるか？',
    options: {
      a: 'let: できる, const: できる',
      b: 'let: できる, const: できない',
      c: 'let: できない, const: できる',
      d: 'let: できない, const: できない',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/let-and-const',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const num : ○○= 123456789;'],
    questionText: '変数numを整数のみ代入できるように型注釈せよ',
    options: { a: 'any', b: 'number', c: 'string', d: 'bigint' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/bigint',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '以下の変数宣言のうち、使うべきでない変数宣言はどれか',
    options: { a: 'var', b: 'let', c: 'const' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/vars-problems',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let x = 1;', 'x = "hello";'],
    questionText: 'コードにおいて、TSではどのようなエラーが起きるか',
    options: {
      a: '変数宣言がlet',
      b: 'xがstring型ではない',
      c: 'シングルクォーテーションを使うべき',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/type-inference',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let x = 1;', 'x = "hello";', 'console.log(x.substring(1,3));'],
    questionText: 'JSでは、上のコードはエラーが起こるか',
    options: { a: '起こる', b: '起こらない' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/difference-between-type-inference-and-dynamic-typing',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: 'TSのnumber型の宣言において、エラーにならないのはどれか',
    options: { a: '_100', b: '100_000_000', c: '100_', d: '100._0' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/number',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: 'TSのnumber型の宣言において、エラーになるのはどれか',
    options: { a: '123', b: '-123', c: '.123', d: '123._0' },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/values-types-variables/number',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const price = parseInt("百円");', 'console.log(price);'],
    questionText: 'JavaScriptにおいて、以下のコードではpriceはどのような値になるでしょう',
    options: { a: 'False', b: 'NaN', c: 'null', d: '百円' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/number',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['console.log(NaN == NaN);'],
    questionText: 'JavaScriptにおいて、以下のコードはどうなる?',
    options: { a: 'True', b: 'False' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/number',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['0.1 + 0.2 === 0.3;'],
    questionText: 'JavaScriptにおいて、以下のコードはどうなる?',
    options: { a: 'True', b: 'False' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/number/decimal-calculation-error',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['0.5 + 0.25 === 0.75;'],
    questionText: 'JavaScriptにおいて、以下のコードはどうなる?',
    options: { a: 'True', b: 'False' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/number/decimal-calculation-error',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const count = 10;', 'console.log(`現在、○○名が見ています。`);'],
    questionText: '変数を文字列に埋め込むにはどうすればいいか？',
    options: { a: '${count}', b: 'count', c: '$count', d: '{{count}}' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/string',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: 'nullとundefinedとはなにか',
    options: {
      a: 'nullは値がないことを示す値であり、undefinedは変数に値がセットされていないときに使われる',
      b: 'undefinedは値がないことを示す値であり、nullは変数に値がセットされていないときに使われる',
      c: 'nullとundefinedは同義である',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/undefined',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '意図的に不明な値を宣言したいときに使う型は？',
    options: { a: 'undefined', b: 'null', c: 'symbol', d: '{}' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/undefined',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const obj = {};', 'console.log(obj.name);'],
    questionText: '出力結果は？',
    options: { a: 'null', b: 'name', c: 'undefined', d: '{}' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/undefined',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      "const s1 = Symbol('foo');",
      "const s2 = Symbol('foo');",
      'console.log(s1 === s2);',
    ],
    questionText: '出力結果は？',
    options: { a: 'True', b: 'False' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/symbol',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const x = 100'],
    questionText: 'この変数をbigint型にするには',
    options: {
      a: 'const x: bigint = 100;',
      b: 'const x: bigint = 100n;',
      c: 'const x: BigInt = 100;',
      d: 'const x: bigInt = 100n;',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/bigint',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ["const str = 'abc';", 'str.length;', 'str.toUpperCase();'],
    questionText:
      'プリミティブ型であるstrにオブジェクトの関数を使っています。これはどのような問題があるか。',
    options: {
      a: 'プリミティブ型にオブジェクトの関数は使えないのでエラーになる',
      b: 'const strObject = new String(str); のような記述がstrの宣言後に必ず必要',
      c: '問題なし',
    },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/boxing',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ["console.log('1' - 1);"],
    questionText: 'TypeScriptでは、実行結果はどうなるか',
    options: { a: 'エラー', b: '11', c: '0', d: 'null' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/type-coercion',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText:
      'let num = 1 にて、1と2と3のみに値を限定して入れたい場合はどういう変数宣言をすればいいか',
    options: {
      a: 'let num: 1 | 2 | 3 = 1;',
      b: 'let num: number = 1, 2, 3;',
      c: 'let num = 1, 2, 3;',
      d: 'let num = 1 || 2 || 3;',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/literal-types',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const n1: Number = 0;', 'const n2: number = n1;'],
    questionText: 'TypeScriptでエラーが起きるか？',
    options: { a: 'True', b: 'False' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/boxing',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const x1: unknown = 10;',
      'const x2: any = 10;',
      'const int1: number = x1;',
      'const int2: number = x2;',
    ],
    questionText: 'エラーが起きるのはどの変数を宣言した行か？',
    options: { a: 'x1', b: 'x2', c: 'int1', d: 'int2' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/statements/any-vs-unknown',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const object1 = { value: 123 };',
      'const object2 = { value: 123 };',
      'console.log(object1 == object2);',
    ],
    questionText: '何が出力されるか？',
    options: { a: 'true', b: 'false', c: 'type: boolean' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ["const str = 'a';", 'const num = str as unknown as number;'],
    questionText: '変数numを宣言時にエラーが起きるか？',
    options: { a: 'True', b: 'False' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/statements/unknown',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const product = {',
      "  name: 'ミネラルウォーター',",
      '  price: 100,',
      '  getTaxIncludedPrice: function () {',
      '    return Math.floor(this.price * 1.1);',
      '  },',
      "  shomikigen: new Date('2022-01-20'),",
      '};',
    ],
    questionText:
      'productオブジェクト内にある、getTaxIncludedPriceメソッドを実行したい。どのように記述すればいいか？',
    options: {
      a: 'getTaxIncludedPrice()',
      b: 'product.getTaxIncludedPrice()',
      c: 'product.getTaxIncludedPrice',
      d: 'product.getTaxIncludedPrice.function()',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/properties-of-objects',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ["const obj = { name: 'dog' }", "obj.name = 'cat';"],
    questionText: '2行目でエラーが起きますか？',
    options: { a: 'True', b: 'False' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/properties-of-objects',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let person: { name: string; age: number };', "person = { name: 'Alice' };"],
    questionText: 'このコードだとエラーが起こります。理由を選択せよ。',
    options: {
      a: 'name プロパティが number であるべきだから',
      b: 'age プロパティが不足しているから',
      c: 'person には代入できない型が使われているから',
      d: 'person の型定義が間違っているから',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/type-annotation-of-objects',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let obj: { foo: number; };', 'obj = { foo: 1 };', 'obj.foo = 2;'],
    questionText: 'このコードで読み取り専用にするにはどうすればいいか？',
    options: {
      a: 'let obj: { readonly foo: number; };',
      b: 'let obj: readonly { foo: number; };',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/readonly-property',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'type Size = {',
      '  width?: number;',
      '  height: number;',
      '};',
      'const size: Size = { height: 10 };',
    ],
    questionText: 'このコードでエラーは起きるか？',
    options: { a: 'True', b: 'False' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/optional-property',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let onlyX: { x: number };', 'onlyX = { x: 1 };', 'onlyX = { x: 1, y: 2 };'],
    questionText: 'このコードでエラーは起きるか？',
    options: { a: 'True', b: 'False' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/excess-property-checking',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const xy: { x: number; y: number } = { x: 1, y: 2 };',
      'let onlyX: { x: number };',
      'onlyX = xy;',
    ],
    questionText: 'このコードでエラーは起きるか？',
    options: { a: 'True', b: 'False' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/excess-property-checking',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let obj: { [K: string]: number; };'],
    questionText: '変数objに代入できるデータは以下のうちどれか？',
    options: {
      a: "{ 1: 'Hello' }",
      b: "{ 'Hello': 1 , 'Bye': 2 }",
      c: '{ arr[]: 1 }',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/index-signature',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: 'JavaScriptのオブジェクト生成はクラスベースかプロトタイプベースか？',
    options: { a: 'クラスベース', b: 'プロトタイプベース' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/prototype-based-programming',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let a: object;'],
    questionText: '変数aに代入できないものを選んでください。',
    options: { a: '{ x: 1 }', b: '[1, 2, 3]', c: 'undefined', d: '/a-z/' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/difference-among-object-and-object',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let a: {};'],
    questionText: 'tsconfig.json で strictが trueの場合、変数aに代入できないものを選んでください。',
    options: { a: 'a = true;', b: 'a = [];', c: 'a = undefined;' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/difference-among-object-and-object',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const item = {a: 1, b: 2, c: 3};'],
    questionText: 'オブジェクトitemのプロパティをまとめて変数として宣言する方法は？',
    options: {
      a: 'const {a, b, c} = item;',
      b: 'const {a, b, c} = {item.a, item.b, item.c}',
      c: 'const a, b, c = item;',
      d: 'const a, b, c = item(a, b, c);',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/destructuring-assignment-from-objects',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const color = { r: 0, g: 1, b: 2, a: 3 };',
      'const { r: red, g: green, b: blue, a: alpha } = color;',
      'console.log(green);',
    ],
    questionText: 'この出力結果はなにか？',
    options: { a: '1', b: '""', c: '{}', d: 'undefined' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/destructuring-assignment-from-objects',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const obj = { a: undefined, b: 111 };',
      'const { a = 0, b = 0 } = obj;',
      'console.log(a, b);',
    ],
    questionText: '出力結果は？',
    options: { a: '0, 0', b: '0, 111', c: 'undefined, 111', d: 'undefined, 0' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/destructuring-assignment-from-objects',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const book = {title: "サバイバルTypeScript"};',
      'const title = book === null || book === undefined ? undefined : book.title;',
    ],
    questionText: '2行目と同じ動作のコードを選択してください。',
    options: {
      a: 'const title = book?.title;',
      b: 'const title = book.?title;',
      c: 'const title = if book === undefined || null else book.title;',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/optional-chaining',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'type AB = { a: string; b: string; }',
      'const a = "aaa";',
      'const b = "bbb";',
      'const ab : AB = { a, b };',
    ],
    questionText: '4行目でエラーは起きますか？',
    options: { a: 'True', b: 'False' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/shorthand-property-names',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const increment = (n) => n + 1;',
      'const result = increment();',
      'console.log(result);',
    ],
    questionText:
      '2行目のincrement関数にオプショナルチェーンをつけて、nullやundefinedのプロパティを誤って参照しないようにしてください。',
    options: {
      a: 'const result = increment?.(1);',
      b: 'const result = increment(1);',
      c: 'const ?result = increment(1);',
      d: 'const ?result = increment?.(1);',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/optional-chaining',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const foo = { a: 1, b: 2, c: 3 };', 'console.log(Object.getPrototypeOf(foo));'],
    questionText: '何が出力されるか？',
    options: { a: 'Object', b: '{ a: 1, b: 2, c: 3 }', c: 'foo', d: '{}' },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/how-to-loop-an-object',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const foo = { a: 1, b: 2, c: 3 };', 'console.log(Object.keys(foo));'],
    questionText: '出力結果は？',
    options: { a: '[1,2,3]', b: '["a","b","c"]', c: '[["a",1],["b",2],["c", 3]]' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/object/how-to-loop-an-object',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['class Person { walk() {} }', 'class Dog { walk() {} }'],
    questionText: 'クラスPersonのインスタンスにDogのインスタンスは代入可能か？',
    options: { a: 'True', b: 'False' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/structural-subtyping',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: 'number型だけの配列を宣言するには？ 配列名はarrayとする。',
    options: {
      a: 'let array: number[];',
      b: 'let array[] :number;',
      c: 'let array: Array<T>;',
      d: 'let array[]: number[];',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/type-annotation-of-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const list1 = [1, 2, 3];',
      'const list2 = [1, 2, 3];',
      'console.log(list1 == list2);',
    ],
    questionText: 'この出力は？',
    options: { a: 'true', b: 'false' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/array-as-a-object',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const arr = [1,2,3];',
      'const backup = arr;',
      'arr.push(4);',
      'console.log(backup);',
    ],
    questionText: '出力結果は？',
    options: { a: '[1,2,3]', b: '[1,2,3,4]', c: 'undefined', d: '[]' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/array-as-a-object',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const abc = ["a", "b", "c"];', 'console.log(abc[100]);'],
    questionText: 'この出力結果は？',
    options: { a: 'エラーが起こる', b: 'null', c: 'undefined', d: 'c' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/how-to-access-elements-in-an-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const nums: number[] = [1, 2, 3];'],
    questionText: 'このコードを読み取り専用にしてください。',
    options: {
      a: 'const nums: asReadonly number[] = [1, 2, 3];',
      b: 'const nums: number[] readonly = [1, 2, 3];',
      c: 'const nums: readonly number[] = [1, 2, 3];',
    },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/readonly-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const arr = [1,2,3,4];', 'const [ , a, b, c] = arr;', 'console.log(a);'],
    questionText: '出力結果は？',
    options: { a: '1', b: '2', c: '3', d: 'undefined' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/destructuring-assignment-from-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const arr = [1,2,3,4];', 'const [ a, ...b] = arr;', 'console.log(b);'],
    questionText: '出力結果は？',
    options: { a: '1', b: '4', c: '[1, 2, 3, 4]', d: '[2, 3, 4]' },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/destructuring-assignment-from-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const nums1 = [1, 2];',
      'const nums2 = [3, 4];',
      'const all = nums1.concat(nums2);',
      'console.log(nums1);',
    ],
    questionText: '出力結果は？',
    options: { a: '[1, 2]', b: '[3, 4]', c: '[1, 2, 3, 4]' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/array-operations',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const arr = ["a", "b", "c"];',
      'arr.forEach((value, i) => {',
      '  console.log(value, i);',
      '});',
    ],
    questionText: '何が出力されるか？',
    options: { a: '0 1 2', b: 'a b c', c: 'a 0\nb 1\nc 2' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/how-to-loop-an-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const arr = ["a", "b", "c"];',
      'const arr2 = arr.map((value) => value + value);',
      'console.log(arr2);',
    ],
    questionText: '何が出力されますか？',
    options: {
      a: '["aa", "bb", "cc"]',
      b: '["a+a","b+b", "c+c" ]',
      c: '{ "aa", "bb", "cc" }',
      d: '["a+a","b+b", "c+c" ]',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/how-to-loop-an-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const arr = [1, 2, 3];', 'const arr2 = [0, ...arr, 4];'],
    questionText: 'arr2にはどんな値が入っているか？',
    options: { a: '[1, 2, 3]', b: '[1, 2, 3, 0, 4]', c: '[0, 1, 2, 3, 4]', d: '[0, 1, 4]' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/spread-syntax-for-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const arr = [1, 2, 3];',
      'const backup = [...arr];',
      'arr.push(4);',
      'console.log(backup);',
    ],
    questionText: '出力結果は？',
    options: { a: '[1, 2, 3]', b: '[1, 2, 3, 4]', c: 'undefined', d: 'never' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/values-types-variables/array/spread-syntax-for-array',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['function getTuple() {', '  return [42, "hello", false];', '}'],
    questionText: '正しい戻り値の型は？',
    options: { a: 'any[]', b: '[number, string, boolean]', c: 'unknown[]', d: 'Array<any>' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/tuple',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const data: [number, string, boolean] = [10, "ok", true];'],
    questionText:
      'タプルの型 [number, string, boolean] を持つ変数 data があるとき、次のうちコンパイルエラーになるコードはどれでしょう？',
    options: {
      a: 'console.log(data[0].toExponential());',
      b: 'console.log(data[1].length);',
      c: 'console.log(data[2].valueOf());',
      d: 'console.log(data[3]);',
    },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/values-types-variables/tuple',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['enum Position {', '  Top,', '  Right,', '  Bottom,', '  Left', '}'],
    questionText: 'enum.Rightの値はどれか？',
    options: { a: '"Right"', b: 'b', c: '1', d: '2' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/enum/numeric-enum',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let a: number | undefined;'],
    questionText: 'このコードで代入してはいけない値は何か？',
    options: { a: '100', b: 'undefined', c: 'any' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/union',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['type X = string & number;', 'let value: X = "Hello";'],
    questionText: 'このコードの結果は？',
    options: {
      a: 'HelloがXに代入され、正常に動作する',
      b: 'Xはstringかnumberのどちらかを持つ型なので、valueの定義は正しい',
      c: 'Xはnever型になり、エラーになる',
      d: 'Xはstringもnumberも受け付けるため、問題なくコンパイルできる',
    },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/intersection',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const num = 123;', 'const str: string = num as string;'],
    questionText: 'TypeScript コードをコンパイルすると、どのような結果になるか？',
    options: {
      a: 'num を string に変換できるので、正常に動作する',
      b: 'num は string にアサーションできないため、コンパイルエラーになる',
      c: 'num は string にアサーションできるが、実行時エラーになる',
      d: 'as は型の変換を行うので、num は "123" になる',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/type-assertion-as',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['console.log(typeof Symbol());'],
    questionText: '何が出力されるか？',
    options: { a: 'undefined', b: 'Symbol', c: 'function', d: 'object' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/values-types-variables/typeof-operator',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const array = [null, 3, 0, null, 1, 2];',
      'console.log(array.filter((n) => n));',
    ],
    questionText: '何が出力されるか？',
    options: { a: '[null, 3, 0, null, 1, 2]', b: '[3, 0, 1, 2]', c: '[3, 1, 2]' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/values-types-variables/truthy-falsy-values',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['if (true) { var a = 10; let b = 20; }', 'console.log(a);', 'console.log(b);'],
    questionText: 'このコードを実行するとどうなるか？',
    options: {
      a: '10 と 20 が出力される',
      b: '10 が出力され、 b に対する ReferenceError が発生する',
      c: 'a に対する ReferenceError が発生し、 b も ReferenceError になる',
      d: 'undefined と 20 が出力される',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/statements/variable-scope',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const result = 10 > 5 ? "greater" : "smaller";', 'console.log(result);'],
    questionText: 'このコードを実行すると？',
    options: { a: '"greater"', b: '"smaller"', c: 'true', d: 'false' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/statements/ternary-operator',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const arr = ["a", "b", "c"];',
      'for (const item of arr) { console.log(item); }',
    ],
    questionText: 'このコードの実行結果は？',
    options: { a: '"a" "b" "c"', b: '["a", "b", "c"]', c: 'undefined' },
    answer: 'a',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const value = "B";',
      'switch (value) {',
      '  case "A": console.log("A");',
      '  case "B": console.log("B");',
      '  case "C": console.log("C");',
      '}',
    ],
    questionText: 'このコードの実行結果は？',
    options: { a: '"A"', b: '"B"', c: '"B" "C"', d: 'エラー' },
    answer: 'c',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const num = 1;',
      'switch (num) {',
      '  case 1: console.log("One");',
      '  case 2: console.log("Two");',
      '}',
    ],
    questionText: 'このコードの実行結果は？',
    options: { a: '"One"', b: '"One" "Two"', c: '"Two"', d: 'エラー' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['try {', '  throw "Error!";', '} catch (e) {', '  console.log(e);', '}'],
    questionText: 'このコードの実行結果は？',
    options: { a: '"Error!"', b: 'エラー発生', c: 'undefined', d: 'コンパイルエラー' },
    answer: 'a',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['function fail(): never {', '  throw new Error("Failure");', '}'],
    questionText: '関数failの戻り値の型は？',
    options: { a: 'void', b: 'never', c: 'any', d: 'unknown' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'function isString(value: unknown): value is string {',
      '  return typeof value === "string";',
      '}',
    ],
    questionText: '関数 isString の目的は？',
    options: {
      a: 'value が string 型かどうかをチェックする',
      b: 'value を string に変換する',
      c: 'value を any に変換する',
      d: 'value を unknown に変換する',
    },
    answer: 'a',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['let x: unknown = "hello";', 'x.toUpperCase();'],
    questionText: 'このコードの実行結果は？',
    options: { a: '"HELLO"', b: 'コンパイルエラー', c: 'undefined', d: 'エラーなし' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'let a: any = "hello";',
      'let b: unknown = "hello";',
      'a.toUpperCase(); // OK',
      'b.toUpperCase(); // ?',
    ],
    questionText: 'b.toUpperCase() の実行結果は？',
    options: { a: 'HELLO', b: 'コンパイルエラー', c: 'undefined', d: '実行時エラー' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['console.log(a);', 'var a = 10;'],
    questionText: 'このコードの出力は？',
    options: { a: '10', b: 'undefined', c: 'ReferenceError', d: 'null' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['throw new Error("Oops!");'],
    questionText: 'このコードの実行結果は？',
    options: { a: 'undefined が出力される', b: '例外が発生する', c: 'エラーなしで実行される' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['const point = { x: 135, y: 35 };'],
    questionText: '変数pointからオブジェクトの型を定義する方法は？',
    options: {
      a: 'type p = type(point);',
      b: 'type p = type point',
      c: 'type p = typeof point;',
      d: 'type p = keyof point;',
    },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/type-reuse/typeof-type-operator',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'type xyz = {',
      '  x: string;',
      '  y: number;',
      '  z: number;',
      '};',
      'type xyzKey = keyof xyz;',
    ],
    questionText: '型xyzの値を選んでください',
    options: {
      a: '["x", "y", "z"]',
      b: '{x: string, y: number, z: number}',
      c: '[string, number, number]',
      d: '"x" | "y" | "z"',
    },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/type-reuse/keyof-type-operator',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '全プロパティを必須にするユーティリティ型は？',
    options: { a: 'Required<T>', b: 'Readonly<T>', c: 'Partial<T>', d: 'NonInfer<T>' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/required',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '全プロパティを読み取り専用にするユーティリティ型は？',
    options: { a: 'Required<T>', b: 'Readonly<T>', c: 'Partial<T>', d: 'NonInfer<T>' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/readonly',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '全プロパティをオプショナルにするユーティリティ型は？',
    options: { a: 'Required<T>', b: 'Readonly<T>', c: 'Partial<T>', d: 'NonInfer<T>' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/partial',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '型推論を防ぐためのユーティリティ型は？',
    options: { a: 'Required<T>', b: 'Readonly<T>', c: 'Partial<T>', d: 'NonInfer<T>' },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/no-infer',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: 'Keyの型を指定したオブジェクト型を定義できるユーティリティ型は？',
    options: { a: 'Record<Keys, Type>', b: 'NonNullable<T>', c: 'ReturnType<T>', d: 'Awaited<T>' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/record',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: 'nullとundefinedを除外するユーティリティ型は？',
    options: { a: 'Record<Keys, Type>', b: 'NonNullable<T>', c: 'ReturnType<T>', d: 'Awaited<T>' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/nonnullable',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '関数の戻り値の型を取得するユーティリティ型は？',
    options: { a: 'Record<Keys, Type>', b: 'NonNullable<T>', c: 'ReturnType<T>', d: 'Awaited<T>' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/return-type',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: 'Promiseの解決値の型を取得するユーティリティ型は？',
    options: { a: 'Record<Keys, Type>', b: 'NonNullable<T>', c: 'ReturnType<T>', d: 'Awaited<T>' },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/awaited',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '任意のプロパティだけを持つオブジェクト型を作るユーティリティ型は？',
    options: { a: 'Pick<T,Keys>', b: 'Omit<T, Keys>', c: 'Exclude<T, U>', d: 'Extract<T,U>' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/pick',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '任意のプロパティを除いたオブジェクト型を作るユーティリティ型は？',
    options: { a: 'Pick<T,Keys>', b: 'Omit<T, Keys>', c: 'Exclude<T, U>', d: 'Extract<T,U>' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/omit',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '既存の型から任意の型を除外するユーティリティ型は？',
    options: { a: 'Pick<T,Keys>', b: 'Omit<T, Keys>', c: 'Exclude<T, U>', d: 'Extract<T,U>' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/exclude',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '既存の型から任意の型だけ抽出するユーティリティ型は？',
    options: { a: 'Pick<T,Keys>', b: 'Omit<T, Keys>', c: 'Exclude<T, U>', d: 'Extract<T,U>' },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/type-reuse/utility-types/extract',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['type A = "a" | "b" | "c";', 'type B = {', '  [key in A]: string;', '};'],
    questionText: '型Bで宣言できる変数は？',
    options: {
      a: 'const a: B = "a" | "b" | "c";',
      b: 'const a: B = ["a", "b", "c"];',
      c: 'const a: B = { a: "a", b: "b" };',
      d: 'const a: B = { a: "a", b: "b", c: "c" };',
    },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/type-reuse/mapped-types',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['type Foo = { a: number; b: string; c: boolean };', 'type T = Foo[keyof Foo];'],
    questionText: '型Tと同じ型は？',
    options: {
      a: '["a", "b", "c"]',
      b: '[number, string, boolean]',
      c: '{a: number, b: string, c: boolean}',
      d: 'number | string | boolean',
    },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/type-reuse/indexed-access-types',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'type Status = ["success", "error", "loading"];',
      'type StatusType = Status[number];',
    ],
    questionText: 'StatusTypeの型は？',
    options: {
      a: 'string',
      b: 'string[]',
      c: '[string, string, string]',
      d: '"success" | "error" | "loading"',
    },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/type-reuse/indexed-access-types',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'type IsString<T> = T extends string ? "YES" : "NO";',
      'type Test = IsString<number>;',
    ],
    questionText: '型Testはどのような型？',
    options: { a: 'string', b: 'number', c: '"YES"', d: '"NO"' },
    answer: 'd',
    link: 'https://typescriptbook.jp/reference/type-reuse/conditional-types',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['console.log(1);', 'await Promise.resolve();', 'console.log(2);'],
    questionText: 'このコードの出力結果は？',
    options: { a: '1 2', b: '2 1', c: 'Error', d: 'なにも出力されない' },
    answer: 'c',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'Promise.reject("Error!")',
      '  .catch((err) => {',
      '    console.log(err);',
      '  })',
      '  .then(() => {',
      '    console.log("Recovered");',
      '  });',
    ],
    questionText: 'このコードのコンソール出力は？',
    options: {
      a: '"Error!"',
      b: '"Error!" → "Recovered"',
      c: '"Recovered"',
      d: '何も表示されない',
    },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'console.log(1);',
      'Promise.resolve().then(() => console.log(2));',
      'console.log(3);',
    ],
    questionText: 'このコードのコンソール出力は？',
    options: { a: '1 2 3', b: '1 3 2', c: '2 1 3', d: '3 1 2' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '次のうち、Promiseの状態として存在しないものはどれでしょうか？',
    options: { a: 'pending', b: 'resolved', c: 'fulfilled', d: 'rejected' },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/asynchronous/promise',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'const names = ["Yamamoto", "Matsumoto", "Sato"];',
      'const nameLengths = names.map(____);',
    ],
    questionText:
      'この map メソッドは各名前の文字数を数値として返すものとします。適切なジェネリクスの型注釈を選んでください。',
    options: {
      a: 'names.map<string>(name => name.length);',
      b: 'names.map<number>(name => name.length);',
      c: 'names.map<boolean>(name => name.length);',
      d: 'names.map<Array<number>>(name => name.length);',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/generics/built-in-libraries-using-generics',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: ['function identity<???>(value: ???): ??? {', '  return value;', '}'],
    questionText: '次の関数 identity で、正しい型変数の使い方はどれでしょうか？',
    options: {
      a: 'function identity<T>(value: T): T',
      b: 'function identity<U>(value: U): T',
      c: 'function identity<X>(value: X): number',
      d: 'function identity(value: T): T',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/generics/type-variables',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'function red<T>(element: T) {',
      '  element.style.backgroundColor = "red";',
      '}',
    ],
    questionText: 'この関数に適切な型制約をつけるには？',
    options: {
      a: 'T extends HTMLElement',
      b: 'T extends object',
      c: 'T extends any',
      d: 'T & HTMLElement',
    },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/generics/type-parameter-constraint',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'type FilterString<T> = T extends string ? T : never;',
      'type Result = FilterString<string | number | boolean>;',
    ],
    questionText: '型Resultの型は？',
    options: { a: 'string', b: 'never', c: 'string | number | boolean', d: 'undefined' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/type-reuse/conditional-types',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'type ElementType<T> = T extends (infer U)[] ? U : never;',
      'type T = ElementType<string[]>;',
    ],
    questionText: '型Tの値は？',
    options: { a: 'string', b: 'string[]', c: 'never', d: 'infer' },
    answer: 'a',
    link: 'https://typescriptbook.jp/reference/type-reuse/conditional-types',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'interface Serializable<T extends string | number = ???> {',
      '  value: T;',
      '  toString(): string;',
      '}',
    ],
    questionText:
      'デフォルト値を指定するのに、Serializable インターフェースの定義で、正しいものはどれか？',
    options: { a: 'bigint', b: 'number', c: 'boolean', d: 'object' },
    answer: 'b',
    link: '',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: null,
    questionText: '共変性（Covariance）とは何か？',
    options: {
      a: '親の型を子の型として扱える',
      b: '子の型を親の型として扱える',
      c: 'どちらの型も変更できない',
      d: 'どちらの型も自由に変更できる',
    },
    answer: 'b',
    link: 'https://typescriptbook.jp/reference/generics/variance',
    wrongs: 0,
    isShowed: false,
  },
  {
    questionCode: [
      'type Wrapper<T> = { value: T; };',
      'type IsString<T> = T extends string ? true : false;',
      'type A = IsString<string | number>;',
    ],
    questionText: '型Aの値は？',
    options: { a: 'string', b: 'number', c: 'boolean', d: 'string | false' },
    answer: 'c',
    link: 'https://typescriptbook.jp/reference/type-reuse/union-distribution',
    wrongs: 0,
    isShowed: false,
  },
];
