name: Deploy Quasar to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Node.js をセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 依存関係をインストール
        run: |
          npm install -g @quasar/cli
          npm install

      - name: Quasar をビルド
        run: quasar build

      - name: `gh-pages` にデプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/spa
          publish_branch: gh-pages
